### ISSUE TITLE
provide an option in settings to remove /r/all and keep only "Your subreddits"

### ISSUE THREAD

**Issue by ajh3** [ajh3/NoSurfForReddit#24]

**Comment by NilsIrl** [comment]
If this is ever done, why not consider having it as the default?

**Comment by ajh3** [comment]
implemented in 9864c1f, and will be included in upcoming v7 release.

For now I am keeping /r/all on by default. This is so the user can immediately try the app after installing it (without having to log in to see any posts whatsoever).
